### ISSUE TITLE
Mac IOS, unable to build

### ISSUE THREAD

**Issue by divanvb** [duddu/cordova-plugin-antitampering#13]
Hi

I'm trying to install this plugin on my mac to build to ios device but I get an error stating it can't install the plugin because it can't find the module '../cordova/metadata/ios_parser'

Any help would be appreciated

**Comment by duddu** [comment]
Hi,
Could you please provide Cordova version output?
The error occurs trying to build from Cordova CLI, right? If you remove
this plugin and try to build your project again, is everything working?


Il giorno mar 19 dic 2017 alle 10:40 divanvb <notifications@github.com> ha
scritto:

**Comment by divanvb** [comment]
Hi

Yes removing it allows the project to build fine. I'm using Ionic with the build process and the Cordova CLI version = 7.1.0

**Comment by duddu** [comment]
Ok thank you,
I'll have a look during this week.
Thanks for reporting

Il giorno mer 20 dic 2017 alle 09:23 divanvb <notifications@github.com> ha
scritto:

**Comment by divanvb** [comment]
For some reason, it's crashing my android application now as well. Was forced to remove the plugin from my application in order to build successfully and have it run on the device.

```32041-32041/com.smartdoc.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.smartdoc.app/com.smartdoc.app.MainActivity}: com.duddu.antitampering.c: Anti-Tampering check failed
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2110)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
                                                                      at android.app.ActivityThread.access$700(ActivityThread.java:140)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                      at android.os.Looper.loop(Looper.java:137)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:4921)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:511)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
                                                                      at dalvik.system.NativeStart.main(Native Method)
                                                                   Caused by: com.duddu.antitampering.c: Anti-Tampering check failed
                                                                      at com.duddu.antitampering.AntiTamperingPlugin$1.run(SourceFile:33)
                                                                      at android.app.Activity.runOnUiThread(Activity.java:4784)
                                                                      at com.duddu.antitampering.AntiTamperingPlugin.a(SourceFile:30)
                                                                      at com.duddu.antitampering.AntiTamperingPlugin.initialize(SourceFile:21)
                                                                      at org.apache.cordova.CordovaPlugin.privateInitialize(SourceFile:57)
                                                                      at org.apache.cordova.PluginManager.getPlugin(SourceFile:171)
                                                                      at org.apache.cordova.PluginManager.startupPlugins(SourceFile:97)
                                                                      at org.apache.cordova.PluginManager.init(SourceFile:86)
                                                                      at org.apache.cordova.CordovaWebViewImpl.init(SourceFile:115)
                                                                      at org.apache.cordova.CordovaActivity.init(SourceFile:149)
                                                                      at org.apache.cordova.CordovaActivity.loadUrl(SourceFile:224)
                                                                      at com.smartdoc.app.MainActivity.onCreate(SourceFile:39)
                                                                      at android.app.Activity.performCreate(Activity.java:5206)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135) 
                                                                      at android.app.ActivityThread.access$700(ActivityThread.java:140) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:4921) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794) 
                                                                      at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by alemarra89** [comment]
Hi folks!! Are there any news about this issue?
My environment:
- OS: macOS Sierra
- Cordova: 8.0.0
- Cordova platform: iOS 4.5.4

My problem is the same: Error: Cannot find module '../cordova/metadata/ios_parser'
PS: this happens only if I run "cordova build ios **--release**" (without --release it works)

Thanks

**Comment by duddu** [comment]
Hi all, 
Some of the Cordova apis we are using changed after version 6; I have added the switch logic to handle the changes, but still have to add the tests (SauceLabs too) before pushing. 
I’ll try to address the remaining work asap, it was so difficult to find any time in the last months, sorry to keep you waiting!

**Comment by fabrz** [comment]
@duddu Any update on this? Thanks for your work.

**Comment by duddu** [comment]
@fabrz, @alemarra89, @marshall9000, @divanvb
Version [0.3.0](https://github.com/duddu/cordova-plugin-antitampering/pull/18) released, issues regarding Cordova 7-8 should be fixed now; sorry for the wait.
I added scheduled [tests](https://travis-ci.org/duddu/cordova-plugin-antitampering/builds/387558169) for all the major Cordova versions (since 5), to be sure to get alerted when new apis break something.

**Comment by duddu** [comment]
I’m closing this issue (since the fallback solution for ios_parser has been implemented and tests are green), feel free to comment if you still get errors on this bit.
