### ISSUE TITLE
path is wrong

### ISSUE THREAD

**Issue by GBoll** [duddu/cordova-plugin-antitampering#14]
I do not feel qualified to stick my fingers into the code in the area regarding security.

Error on Cordova CLI install

```
MacBook-Pro:simp harddrive$ sudo cordova plugin add cordova-plugin-antitampering --variable ENABLE_DEBUG_DETECTION=true --save
Installing "cordova-plugin-antitampering" for android
Android Studio project detected
[ANTI-TAMPERING] Enabling debug detection for android

[ANTI-TAMPERING] ERROR! Unable to read java class source at path /Users/harddrive/projects/ABtest/simp/platforms/android/src/com/duddu/antitampering/AntiTamperingPlugin.java
Failed to install 'cordova-plugin-antitampering': Error: Error: ENOENT: no such file or directory, open '/Users/harddrive/projects/ABtest/simp/platforms/android/src/com/duddu/antitampering/AntiTamperingPlugin.java'
    at exit (/Users/harddrive/projects/ABtest/simp/plugins/cordova-plugin-antitampering/scripts/handle_plugin_preferences.js:88:15)
    at /Users/harddrive/projects/ABtest/simp/plugins/cordova-plugin-antitampering/scripts/handle_plugin_preferences.js:43:17
    at Array.forEach (native)
    at module.exports (/Users/harddrive/projects/ABtest/simp/plugins/cordova-plugin-antitampering/scripts/handle_plugin_preferences.js:24:39)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:188:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:164:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
(node:1165) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error: ENOENT: no such file or directory, open '/Users/harddrive/projects/ABtest/simp/platforms/android/src/com/duddu/antitampering/AntiTamperingPlugin.java'
MacBook-Pro:simp harddrive$
```

STATED TARGET
**simp/platforms**/android/src/com/duddu/antitampering/AntiTamperingPlugin.java'

ACTUALLY CREATED
**simp/node_modules**/cordova-plugin-antitampering/src/android/com/duddu/antitampering/AntiTamperingPlugin.java

**simp/platforms**/android/app/src/main/java/com/duddu/antitampering/AntiTamperingPlugin.java

**simp/plugins**/cordova-plugin-antitampering/src/android/com/duddu/antitampering/AntiTamperingPlugin.java

I guess something needs updating.

**Comment by GBoll** [comment]
For the moment I will just create that path and copy the file there...

**Comment by duddu** [comment]
Hi @GBoll 
The android output structure has changed in the latest Cordova versions. I have updated the plugin to handle that. Check out the latest release [0.3.0](https://www.npmjs.com/package/cordova-plugin-antitampering) and give it a try.
